-- qsys_core.vhd

-- Generated using ACDS version 20.1 720

library IEEE;
use IEEE.std_logic_1164.all;
use IEEE.numeric_std.all;

entity qsys_core is
	port (
		avm_cs_i          : in    std_logic                     := '0';             --   avm.cs_i
		avm_address_i     : in    std_logic_vector(31 downto 0) := (others => '0'); --      .address_i
		avm_read_i        : in    std_logic                     := '0';             --      .read_i
		avm_waitrequest_o : out   std_logic;                                        --      .waitrequest_o
		avm_readdata_o    : out   std_logic_vector(31 downto 0);                    --      .readdata_o
		avm_write_i       : in    std_logic                     := '0';             --      .write_i
		avm_writedata_i   : in    std_logic_vector(31 downto 0) := (others => '0'); --      .writedata_i
		avm_byteenable_i  : in    std_logic_vector(3 downto 0)  := (others => '0'); --      .byteenable_i
		clk_clk           : in    std_logic                     := '0';             --   clk.clk
		reset_reset_n     : in    std_logic                     := '0';             -- reset.reset_n
		sdram_addr        : out   std_logic_vector(12 downto 0);                    -- sdram.addr
		sdram_ba          : out   std_logic_vector(1 downto 0);                     --      .ba
		sdram_cas_n       : out   std_logic;                                        --      .cas_n
		sdram_cke         : out   std_logic;                                        --      .cke
		sdram_cs_n        : out   std_logic;                                        --      .cs_n
		sdram_dq          : inout std_logic_vector(15 downto 0) := (others => '0'); --      .dq
		sdram_dqm         : out   std_logic_vector(1 downto 0);                     --      .dqm
		sdram_ras_n       : out   std_logic;                                        --      .ras_n
		sdram_we_n        : out   std_logic                                         --      .we_n
	);
end entity qsys_core;

architecture rtl of qsys_core is
	component qsys_core_sdram is
		port (
			clk            : in    std_logic                     := 'X';             -- clk
			reset_n        : in    std_logic                     := 'X';             -- reset_n
			az_addr        : in    std_logic_vector(24 downto 0) := (others => 'X'); -- address
			az_be_n        : in    std_logic_vector(1 downto 0)  := (others => 'X'); -- byteenable_n
			az_cs          : in    std_logic                     := 'X';             -- chipselect
			az_data        : in    std_logic_vector(15 downto 0) := (others => 'X'); -- writedata
			az_rd_n        : in    std_logic                     := 'X';             -- read_n
			az_wr_n        : in    std_logic                     := 'X';             -- write_n
			za_data        : out   std_logic_vector(15 downto 0);                    -- readdata
			za_valid       : out   std_logic;                                        -- readdatavalid
			za_waitrequest : out   std_logic;                                        -- waitrequest
			zs_addr        : out   std_logic_vector(12 downto 0);                    -- export
			zs_ba          : out   std_logic_vector(1 downto 0);                     -- export
			zs_cas_n       : out   std_logic;                                        -- export
			zs_cke         : out   std_logic;                                        -- export
			zs_cs_n        : out   std_logic;                                        -- export
			zs_dq          : inout std_logic_vector(15 downto 0) := (others => 'X'); -- export
			zs_dqm         : out   std_logic_vector(1 downto 0);                     -- export
			zs_ras_n       : out   std_logic;                                        -- export
			zs_we_n        : out   std_logic                                         -- export
		);
	end component qsys_core_sdram;

	component wb_avm_bridge_if is
		port (
			clk             : in  std_logic                     := 'X';             -- clk
			reset           : in  std_logic                     := 'X';             -- reset
			avm_cs          : out std_logic;                                        -- chipselect
			avm_address     : out std_logic_vector(31 downto 0);                    -- address
			avm_read        : out std_logic;                                        -- read
			avm_waitrequest : in  std_logic                     := 'X';             -- waitrequest
			avm_readdata    : in  std_logic_vector(31 downto 0) := (others => 'X'); -- readdata
			avm_write       : out std_logic;                                        -- write
			avm_writedata   : out std_logic_vector(31 downto 0);                    -- writedata
			avm_byteenable  : out std_logic_vector(3 downto 0);                     -- byteenable
			cs_i            : in  std_logic                     := 'X';             -- cs_i
			address_i       : in  std_logic_vector(31 downto 0) := (others => 'X'); -- address_i
			read_i          : in  std_logic                     := 'X';             -- read_i
			waitrequest_o   : out std_logic;                                        -- waitrequest_o
			readdata_o      : out std_logic_vector(31 downto 0);                    -- readdata_o
			write_i         : in  std_logic                     := 'X';             -- write_i
			writedata_i     : in  std_logic_vector(31 downto 0) := (others => 'X'); -- writedata_i
			byteenable_i    : in  std_logic_vector(3 downto 0)  := (others => 'X')  -- byteenable_i
		);
	end component wb_avm_bridge_if;

	component qsys_core_mm_interconnect_0 is
		port (
			clk_sys_clk_clk                                 : in  std_logic                     := 'X';             -- clk
			wb_avm_bridge_reset_reset_bridge_in_reset_reset : in  std_logic                     := 'X';             -- reset
			wb_avm_bridge_m0_address                        : in  std_logic_vector(31 downto 0) := (others => 'X'); -- address
			wb_avm_bridge_m0_waitrequest                    : out std_logic;                                        -- waitrequest
			wb_avm_bridge_m0_byteenable                     : in  std_logic_vector(3 downto 0)  := (others => 'X'); -- byteenable
			wb_avm_bridge_m0_chipselect                     : in  std_logic                     := 'X';             -- chipselect
			wb_avm_bridge_m0_read                           : in  std_logic                     := 'X';             -- read
			wb_avm_bridge_m0_readdata                       : out std_logic_vector(31 downto 0);                    -- readdata
			wb_avm_bridge_m0_write                          : in  std_logic                     := 'X';             -- write
			wb_avm_bridge_m0_writedata                      : in  std_logic_vector(31 downto 0) := (others => 'X'); -- writedata
			sdram_s1_address                                : out std_logic_vector(24 downto 0);                    -- address
			sdram_s1_write                                  : out std_logic;                                        -- write
			sdram_s1_read                                   : out std_logic;                                        -- read
			sdram_s1_readdata                               : in  std_logic_vector(15 downto 0) := (others => 'X'); -- readdata
			sdram_s1_writedata                              : out std_logic_vector(15 downto 0);                    -- writedata
			sdram_s1_byteenable                             : out std_logic_vector(1 downto 0);                     -- byteenable
			sdram_s1_readdatavalid                          : in  std_logic                     := 'X';             -- readdatavalid
			sdram_s1_waitrequest                            : in  std_logic                     := 'X';             -- waitrequest
			sdram_s1_chipselect                             : out std_logic                                         -- chipselect
		);
	end component qsys_core_mm_interconnect_0;

	signal wb_avm_bridge_m0_chipselect                     : std_logic;                     -- wb_avm_bridge:avm_cs -> mm_interconnect_0:wb_avm_bridge_m0_chipselect
	signal wb_avm_bridge_m0_waitrequest                    : std_logic;                     -- mm_interconnect_0:wb_avm_bridge_m0_waitrequest -> wb_avm_bridge:avm_waitrequest
	signal wb_avm_bridge_m0_readdata                       : std_logic_vector(31 downto 0); -- mm_interconnect_0:wb_avm_bridge_m0_readdata -> wb_avm_bridge:avm_readdata
	signal wb_avm_bridge_m0_address                        : std_logic_vector(31 downto 0); -- wb_avm_bridge:avm_address -> mm_interconnect_0:wb_avm_bridge_m0_address
	signal wb_avm_bridge_m0_read                           : std_logic;                     -- wb_avm_bridge:avm_read -> mm_interconnect_0:wb_avm_bridge_m0_read
	signal wb_avm_bridge_m0_byteenable                     : std_logic_vector(3 downto 0);  -- wb_avm_bridge:avm_byteenable -> mm_interconnect_0:wb_avm_bridge_m0_byteenable
	signal wb_avm_bridge_m0_write                          : std_logic;                     -- wb_avm_bridge:avm_write -> mm_interconnect_0:wb_avm_bridge_m0_write
	signal wb_avm_bridge_m0_writedata                      : std_logic_vector(31 downto 0); -- wb_avm_bridge:avm_writedata -> mm_interconnect_0:wb_avm_bridge_m0_writedata
	signal mm_interconnect_0_sdram_s1_chipselect           : std_logic;                     -- mm_interconnect_0:sdram_s1_chipselect -> sdram:az_cs
	signal mm_interconnect_0_sdram_s1_readdata             : std_logic_vector(15 downto 0); -- sdram:za_data -> mm_interconnect_0:sdram_s1_readdata
	signal mm_interconnect_0_sdram_s1_waitrequest          : std_logic;                     -- sdram:za_waitrequest -> mm_interconnect_0:sdram_s1_waitrequest
	signal mm_interconnect_0_sdram_s1_address              : std_logic_vector(24 downto 0); -- mm_interconnect_0:sdram_s1_address -> sdram:az_addr
	signal mm_interconnect_0_sdram_s1_read                 : std_logic;                     -- mm_interconnect_0:sdram_s1_read -> mm_interconnect_0_sdram_s1_read:in
	signal mm_interconnect_0_sdram_s1_byteenable           : std_logic_vector(1 downto 0);  -- mm_interconnect_0:sdram_s1_byteenable -> mm_interconnect_0_sdram_s1_byteenable:in
	signal mm_interconnect_0_sdram_s1_readdatavalid        : std_logic;                     -- sdram:za_valid -> mm_interconnect_0:sdram_s1_readdatavalid
	signal mm_interconnect_0_sdram_s1_write                : std_logic;                     -- mm_interconnect_0:sdram_s1_write -> mm_interconnect_0_sdram_s1_write:in
	signal mm_interconnect_0_sdram_s1_writedata            : std_logic_vector(15 downto 0); -- mm_interconnect_0:sdram_s1_writedata -> sdram:az_data
	signal reset_reset_n_ports_inv                         : std_logic;                     -- reset_reset_n:inv -> [mm_interconnect_0:wb_avm_bridge_reset_reset_bridge_in_reset_reset, wb_avm_bridge:reset]
	signal mm_interconnect_0_sdram_s1_read_ports_inv       : std_logic;                     -- mm_interconnect_0_sdram_s1_read:inv -> sdram:az_rd_n
	signal mm_interconnect_0_sdram_s1_byteenable_ports_inv : std_logic_vector(1 downto 0);  -- mm_interconnect_0_sdram_s1_byteenable:inv -> sdram:az_be_n
	signal mm_interconnect_0_sdram_s1_write_ports_inv      : std_logic;                     -- mm_interconnect_0_sdram_s1_write:inv -> sdram:az_wr_n

begin

	sdram : component qsys_core_sdram
		port map (
			clk            => clk_clk,                                         --   clk.clk
			reset_n        => reset_reset_n,                                   -- reset.reset_n
			az_addr        => mm_interconnect_0_sdram_s1_address,              --    s1.address
			az_be_n        => mm_interconnect_0_sdram_s1_byteenable_ports_inv, --      .byteenable_n
			az_cs          => mm_interconnect_0_sdram_s1_chipselect,           --      .chipselect
			az_data        => mm_interconnect_0_sdram_s1_writedata,            --      .writedata
			az_rd_n        => mm_interconnect_0_sdram_s1_read_ports_inv,       --      .read_n
			az_wr_n        => mm_interconnect_0_sdram_s1_write_ports_inv,      --      .write_n
			za_data        => mm_interconnect_0_sdram_s1_readdata,             --      .readdata
			za_valid       => mm_interconnect_0_sdram_s1_readdatavalid,        --      .readdatavalid
			za_waitrequest => mm_interconnect_0_sdram_s1_waitrequest,          --      .waitrequest
			zs_addr        => sdram_addr,                                      --  wire.export
			zs_ba          => sdram_ba,                                        --      .export
			zs_cas_n       => sdram_cas_n,                                     --      .export
			zs_cke         => sdram_cke,                                       --      .export
			zs_cs_n        => sdram_cs_n,                                      --      .export
			zs_dq          => sdram_dq,                                        --      .export
			zs_dqm         => sdram_dqm,                                       --      .export
			zs_ras_n       => sdram_ras_n,                                     --      .export
			zs_we_n        => sdram_we_n                                       --      .export
		);

	wb_avm_bridge : component wb_avm_bridge_if
		port map (
			clk             => clk_clk,                      --   clock.clk
			reset           => reset_reset_n_ports_inv,      --   reset.reset
			avm_cs          => wb_avm_bridge_m0_chipselect,  --      m0.chipselect
			avm_address     => wb_avm_bridge_m0_address,     --        .address
			avm_read        => wb_avm_bridge_m0_read,        --        .read
			avm_waitrequest => wb_avm_bridge_m0_waitrequest, --        .waitrequest
			avm_readdata    => wb_avm_bridge_m0_readdata,    --        .readdata
			avm_write       => wb_avm_bridge_m0_write,       --        .write
			avm_writedata   => wb_avm_bridge_m0_writedata,   --        .writedata
			avm_byteenable  => wb_avm_bridge_m0_byteenable,  --        .byteenable
			cs_i            => avm_cs_i,                     -- conduit.cs_i
			address_i       => avm_address_i,                --        .address_i
			read_i          => avm_read_i,                   --        .read_i
			waitrequest_o   => avm_waitrequest_o,            --        .waitrequest_o
			readdata_o      => avm_readdata_o,               --        .readdata_o
			write_i         => avm_write_i,                  --        .write_i
			writedata_i     => avm_writedata_i,              --        .writedata_i
			byteenable_i    => avm_byteenable_i              --        .byteenable_i
		);

	mm_interconnect_0 : component qsys_core_mm_interconnect_0
		port map (
			clk_sys_clk_clk                                 => clk_clk,                                  --                               clk_sys_clk.clk
			wb_avm_bridge_reset_reset_bridge_in_reset_reset => reset_reset_n_ports_inv,                  -- wb_avm_bridge_reset_reset_bridge_in_reset.reset
			wb_avm_bridge_m0_address                        => wb_avm_bridge_m0_address,                 --                          wb_avm_bridge_m0.address
			wb_avm_bridge_m0_waitrequest                    => wb_avm_bridge_m0_waitrequest,             --                                          .waitrequest
			wb_avm_bridge_m0_byteenable                     => wb_avm_bridge_m0_byteenable,              --                                          .byteenable
			wb_avm_bridge_m0_chipselect                     => wb_avm_bridge_m0_chipselect,              --                                          .chipselect
			wb_avm_bridge_m0_read                           => wb_avm_bridge_m0_read,                    --                                          .read
			wb_avm_bridge_m0_readdata                       => wb_avm_bridge_m0_readdata,                --                                          .readdata
			wb_avm_bridge_m0_write                          => wb_avm_bridge_m0_write,                   --                                          .write
			wb_avm_bridge_m0_writedata                      => wb_avm_bridge_m0_writedata,               --                                          .writedata
			sdram_s1_address                                => mm_interconnect_0_sdram_s1_address,       --                                  sdram_s1.address
			sdram_s1_write                                  => mm_interconnect_0_sdram_s1_write,         --                                          .write
			sdram_s1_read                                   => mm_interconnect_0_sdram_s1_read,          --                                          .read
			sdram_s1_readdata                               => mm_interconnect_0_sdram_s1_readdata,      --                                          .readdata
			sdram_s1_writedata                              => mm_interconnect_0_sdram_s1_writedata,     --                                          .writedata
			sdram_s1_byteenable                             => mm_interconnect_0_sdram_s1_byteenable,    --                                          .byteenable
			sdram_s1_readdatavalid                          => mm_interconnect_0_sdram_s1_readdatavalid, --                                          .readdatavalid
			sdram_s1_waitrequest                            => mm_interconnect_0_sdram_s1_waitrequest,   --                                          .waitrequest
			sdram_s1_chipselect                             => mm_interconnect_0_sdram_s1_chipselect     --                                          .chipselect
		);

	reset_reset_n_ports_inv <= not reset_reset_n;

	mm_interconnect_0_sdram_s1_read_ports_inv <= not mm_interconnect_0_sdram_s1_read;

	mm_interconnect_0_sdram_s1_byteenable_ports_inv <= not mm_interconnect_0_sdram_s1_byteenable;

	mm_interconnect_0_sdram_s1_write_ports_inv <= not mm_interconnect_0_sdram_s1_write;

end architecture rtl; -- of qsys_core
